### ISSUE TITLE
作業ディレクトリを pipenv 編集可能な依存関係として追加

### ISSUE THREAD

**Issue by soonraah** [soonraah/evening_moon#15]
## 概要

これ。
https://pipenv-ja.readthedocs.io/ja/translate-ja/basics.html#editable-dependencies-e-g-e

しかし一筋縄ではいかない。

## 受け入れ基準

- [x] 編集可能な依存関係として evening_moon を追加

**Comment by soonraah** [comment]
## 依存関係の install

単純にやろうとするとエラーになる。
インストールできない。

```
$ pipenv install --dev -e .
Installing -e .…
Traceback (most recent call last):
  File "/Users/sonoyou/miniconda3/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/core.py", line 1909, in do_install
    pkg_requirement = Requirement.from_line(pkg_line)
  File "/Users/sonoyou/miniconda3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1098, in from_line
    "Error parsing requirement %s -- are you sure it is installable?" % line
pipenv.vendor.requirementslib.exceptions.RequirementError: Error parsing requirement . -- are you sure it is installable?
```

以下のブログ記事を参考に `setup.py` を用意すると実行できた。

- [Pythonのパッケージ周りのベストプラクティスを理解する](https://www.m3tech.blog/entry/python-packaging)

これによると `setup.cfg` も用意した方がよさそうだがいったん置いておく。
